/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/clayton/robo/EZ-Kart/src/ez_kart/msg/Voltmeter.msg
 *
 */


#ifndef EZ_KART_MESSAGE_VOLTMETER_H
#define EZ_KART_MESSAGE_VOLTMETER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ez_kart
{
template <class ContainerAllocator>
struct Voltmeter_
{
  typedef Voltmeter_<ContainerAllocator> Type;

  Voltmeter_()
    : voltage(0.0)  {
    }
  Voltmeter_(const ContainerAllocator& _alloc)
    : voltage(0.0)  {
    }



   typedef double _voltage_type;
  _voltage_type voltage;




  typedef boost::shared_ptr< ::ez_kart::Voltmeter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ez_kart::Voltmeter_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Voltmeter_

typedef ::ez_kart::Voltmeter_<std::allocator<void> > Voltmeter;

typedef boost::shared_ptr< ::ez_kart::Voltmeter > VoltmeterPtr;
typedef boost::shared_ptr< ::ez_kart::Voltmeter const> VoltmeterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ez_kart::Voltmeter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ez_kart::Voltmeter_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ez_kart

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'ez_kart': ['/home/clayton/robo/EZ-Kart/src/ez_kart/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ez_kart::Voltmeter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ez_kart::Voltmeter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ez_kart::Voltmeter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ez_kart::Voltmeter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ez_kart::Voltmeter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ez_kart::Voltmeter_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ez_kart::Voltmeter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd1e97d74e6d797b46bc5a51e820e6ae";
  }

  static const char* value(const ::ez_kart::Voltmeter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd1e97d74e6d797bULL;
  static const uint64_t static_value2 = 0x46bc5a51e820e6aeULL;
};

template<class ContainerAllocator>
struct DataType< ::ez_kart::Voltmeter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ez_kart/Voltmeter";
  }

  static const char* value(const ::ez_kart::Voltmeter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ez_kart::Voltmeter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 voltage\n\
";
  }

  static const char* value(const ::ez_kart::Voltmeter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ez_kart::Voltmeter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voltage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Voltmeter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ez_kart::Voltmeter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ez_kart::Voltmeter_<ContainerAllocator>& v)
  {
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EZ_KART_MESSAGE_VOLTMETER_H
